kind: ConfigMap
apiVersion: v1
metadata:
  name: alertmanager
data:
  config.yml: |-
    global:
      resolve_timeout: 5m
      wechat_api_corp_id: 'wwbaf121ea22b882bc'
      wechat_api_url: 'https://qyapi.weixin.qq.com/cgi-bin/'
      wechat_api_secret: 'osOaUKObyc34AraoNKcqP_fGe85syOk0cKVDiNFsjAI'

    route:
      group_by: ['alertname']
      group_wait: 10s
      group_interval: 10s
      repeat_interval: 1h
      receiver: 'wechat'
    receivers:
    - name: 'wechat'
      wechat_configs:
      - send_resolved: true
        to_party: '1'
        agent_id: 1000002
        corp_id: 'wwbaf121ea22b882bc'
        api_url: 'https://qyapi.weixin.qq.com/cgi-bin/'
        api_secret: 'osOaUKObyc34AraoNKcqP_fGe85syOk0cKVDiNFsjAI'
    inhibit_rules:
      - source_match:
          severity: 'critical'
        target_match:
          severity: 'warning'
        equal: ['alertname', 'dev', 'instance']
