apiVersion: v1
kind: PersistentVolume
metadata:
  name:  grefana
spec:
  capacity: 
    storage: 2Gi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  nfs:
    path: /data/k8s
    server: 192.168.232.163
