apiVersion: v1
kind: Service
metadata:
  labels:
    app: mysqlall
  name: mysqlall
spec:
  type: NodePort
  ports:
  - port: 3306
    protocol: TCP
    targetPort: 3306
    nodePort: 30005
    name: mysql
  - port: 9104
    protocol: TCP
    targetPort: 9104
    name: mysql-exporter
    nodePort: 30006
  selector:
    app: mysqlall
  sessionAffinity: None
