apiVersion: v1
kind: "Service"
metadata:
  name: prometheus
  labels:
    name: prometheus
spec:
  ports:
  - name: prometheus
    port: 9090
    targetPort: 9090
    nodePort: 30003
  selector:
    app: prometheus
  type: NodePort
